redirectsOrigin = "config"
headers = []

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/angular-runtime"

[plugins.inputs]

[build]
publish = "C:\\Users\\admin\\Desktop\\rkinis-naketoba\\dist\\rkinis-naketoba\\browser"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]